name: Deploy to gh-pages

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup git identity (name)
        run: git config --global user.name "Nils Dralle/gh-actions"
      - name: Setup git identity (email)
        run: git config --global user.email "nils.91@googlemail.com"
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Build with NPM
        run: npm install      
      - run: npm run build --if-present
      - name: Deploy to gh-pages
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy