name: Deploy to gh-pages

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 15.x
      - name: Build with NPM
        run: npm install      
      - run: npm run build --if-present
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: 'Nils Dralle/gh-actions[bot]'
          user_email: 'nils.91@googlemail.com'
          commit_message: Auto deploy to gh-pages